# Generated by Django 4.2.1 on 2023-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='taka',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
