# Generated by Django 4.2.1 on 2023-05-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_banner_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='taka',
        ),
    ]
