# Generated by Django 4.2.1 on 2023-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_servicecategory_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=444),
        ),
    ]
